#!/bin/bash

function setintip()
{
	int="$1";
	ipaddr="$2";

	#ifconfig "eth0" 169.254.0.1 netmask 255.255.255.0
	#ifconfig "$int" "$ipaddr" netmask 255.255.255.0

}
setintip "eth0" "192.168.1.70";
ifconfig | grep "broadcast" | awk '{ print $2 } ' ;
# delete default gateway
route del default
# specify a value for the default gateway
route add default gw 192.168.1.254 eth0
nano /etc/resolv.conf
ping 192.168.1.254
leafpad /etc/network/interfaces
###
auto eth0
iface eth0 inet static
address 192.168.1.70
netmask 255.255.255.0
gateway 192.168.1.254
dns-nameserver 8.8.8.8
dns-search www.google.com
leafpad /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
/etc/init.d/networking restart;
systemctl status networking.service  
journalctl -xe
leafpad /etc/resolveconf/resolv.conf.d/tail
